In [ ]:
NumPy and Pandas are popular Python libraries used for data manipulation, analysis, and computation. NumPy provides efficient 
numerical operations on multi-dimensional arrays, while Pandas offers data structures and tools for handling structured data.
Here's an overview of how you can use these libraries to work with data:

In [1]:
# Installing Libraries:
# Before using NumPy and Pandas, you need to install them. You can install them using pip, the package installer for Python. 
# Run the following commands in your command prompt or terminal:
    
pip install numpy
pip install pandas

SyntaxError: invalid syntax (Temp/ipykernel_2400/3830513525.py, line 5)

In [2]:
# Importing Libraries:
    
# After installing the libraries, you need to import them into your Python script or Jupyter Notebook:
    
import numpy as np
import pandas as pd

In [5]:
# Working with NumPy:

# NumPy's main data structure is the NumPy array, which allows efficient operations on multi-dimensional data. You can create 
# arrays using the np.array() function or various other NumPy functions. Here are some common operations:

# Creating an array:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
# Basic operations:

arr2 = arr + 1  # Add 1 to each element
arr3 = arr * 2  # Multiply each element by 2
print(arr2)
print(arr3)

[2 3 4 5 6]
[ 2  4  6  8 10]


In [7]:
# Array indexing and slicing:

print(arr[0])      # Access the first element
print(arr[1:3])    # Access elements at index 1 and 2

1
[2 3]


In [8]:
# Array functions:

print(np.mean(arr))      # Calculate the mean
print(np.max(arr))       # Find the maximum value
print(np.sum(arr))       # Compute the sum

3.0
5
15


In [40]:
# Reshaping an array:

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Reshape the array to a 2x3 matrix

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [41]:
# Mathematical functions:

arr = np.array([1, 2, 3, 4, 5])
np.sqrt(arr)     # Calculate the square root of each element

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [42]:
np.exp(arr)      # Compute the exponential of each element

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [43]:
np.sin(arr)      # Calculate the sine of each element

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [11]:
# Working with Pandas:

# Pandas provides two primary data structures: Series and DataFrame. A Series represents a one-dimensional labeled array, and a 
# DataFrame is a two-dimensional labeled data structure with columns of potentially different types. Here's a brief 
# introduction:

# Creating a Series:

s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [14]:
# Creating a DataFrame:

data = {'Name': ['John', 'Emily', 'Ryan'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Paris', 'London']}
df = pd.DataFrame(data)
print(df)
type(data)

    Name  Age      City
0   John   25  New York
1  Emily   30     Paris
2   Ryan   35    London


dict

In [15]:
# Loading data from a file:

df = pd.read_csv(r'C:\Users\sisir.sahu\Documents\GitHub\Python for Data science\Data Analysis in Python\IPL Matches 2008-2020.csv')
# Load data from a CSV file

In [17]:
# Data manipulation:

df.head()        # Display the first few rows of the DataFrame

id        city        date player_of_match  \
0  335982   Bangalore  2008-04-18     BB McCullum   
1  335983  Chandigarh  2008-04-19      MEK Hussey   
2  335984       Delhi  2008-04-19     MF Maharoof   
3  335985      Mumbai  2008-04-20      MV Boucher   
4  335986     Kolkata  2008-04-20       DJ Hussey   

                                        venue  neutral_venue  \
0                       M Chinnaswamy Stadium              0   
1  Punjab Cricket Association Stadium, Mohali              0   
2                            Feroz Shah Kotla              0   
3                            Wankhede Stadium              0   
4                                Eden Gardens              0   

                         team1                        team2  \
0  Royal Challengers Bangalore        Kolkata Knight Riders   
1              Kings XI Punjab          Chennai Super Kings   
2             Delhi Daredevils             Rajasthan Royals   
3               Mumbai Indians  Royal Challengers Bangalore   
4        Kolkata Knight Riders              Deccan Chargers   

                   toss_winner toss_decision                       winner  \
0  Royal Challengers Bangalore         field        Kolkata Knight Riders   
1          Chennai Super Kings           bat          Chennai Super Kings   
2             Rajasthan Royals           bat             Delhi Daredevils   
3               Mumbai Indians           bat  Royal Challengers Bangalore   
4              Deccan Chargers           bat        Kolkata Knight Riders   

    result  result_margin eliminator method    umpire1         umpire2  
0     runs          140.0          N    NaN  Asad Rauf     RE Koertzen  
1     runs           33.0          N    NaN  MR Benson      SL Shastri  
2  wickets            9.0          N    NaN  Aleem Dar  GA Pratapkumar  
3  wickets            5.0          N    NaN   SJ Davis       DJ Harper  
4  wickets            5.0          N    NaN  BF Bowden     K Hariharan

In [18]:
df.describe()    # Generate summary statistics of the DataFrame

id  neutral_venue  result_margin
count  8.160000e+02     816.000000     799.000000
mean   7.563496e+05       0.094363      17.321652
std    3.058943e+05       0.292512      22.068427
min    3.359820e+05       0.000000       1.000000
25%    5.012278e+05       0.000000       6.000000
50%    7.292980e+05       0.000000       8.000000
75%    1.082626e+06       0.000000      19.500000
max    1.237181e+06       1.000000     146.000000

In [19]:
df['result_margin'].mean() # Calculate the mean of the 'result_margin' column

17.321652065081352

In [20]:
df[df['result_margin'] > 30]  # Filter rows based on a condition

id        city        date player_of_match  \
0     335982   Bangalore  2008-04-18     BB McCullum   
1     335983  Chandigarh  2008-04-19      MEK Hussey   
9     335991  Chandigarh  2008-04-25   KC Sangakkara   
18    336000      Jaipur  2008-05-01     SA Asnodkar   
37    336019  Chandigarh  2008-05-28        SE Marsh   
..       ...         ...         ...             ...   
802  1216538     Sharjah  2020-10-04        TA Boult   
803  1216539       Dubai  2020-09-25         PP Shaw   
804  1216540     Sharjah  2020-10-12  AB de Villiers   
806  1216542       Dubai  2020-10-08     JM Bairstow   
812  1237177       Dubai  2020-11-05       JJ Bumrah   

                                          venue  neutral_venue  \
0                         M Chinnaswamy Stadium              0   
1    Punjab Cricket Association Stadium, Mohali              0   
9    Punjab Cricket Association Stadium, Mohali              0   
18                       Sawai Mansingh Stadium              0   
37   Punjab Cricket Association Stadium, Mohali              0   
..                                          ...            ...   
802                     Sharjah Cricket Stadium              0   
803         Dubai International Cricket Stadium              0   
804                     Sharjah Cricket Stadium              0   
806         Dubai International Cricket Stadium              0   
812         Dubai International Cricket Stadium              0   

                           team1                  team2  \
0    Royal Challengers Bangalore  Kolkata Knight Riders   
1                Kings XI Punjab    Chennai Super Kings   
9                Kings XI Punjab         Mumbai Indians   
18              Rajasthan Royals  Kolkata Knight Riders   
37               Kings XI Punjab       Rajasthan Royals   
..                           ...                    ...   
802               Mumbai Indians    Sunrisers Hyderabad   
803               Delhi Capitals    Chennai Super Kings   
804  Royal Challengers Bangalore  Kolkata Knight Riders   
806          Sunrisers Hyderabad        Kings XI Punjab   
812               Mumbai Indians         Delhi Capitals   

                     toss_winner toss_decision                       winner  \
0    Royal Challengers Bangalore         field        Kolkata Knight Riders   
1            Chennai Super Kings           bat          Chennai Super Kings   
9                 Mumbai Indians         field              Kings XI Punjab   
18              Rajasthan Royals           bat             Rajasthan Royals   
37              Rajasthan Royals         field              Kings XI Punjab   
..                           ...           ...                          ...   
802               Mumbai Indians           bat               Mumbai Indians   
803          Chennai Super Kings         field               Delhi Capitals   
804  Royal Challengers Bangalore           bat  Royal Challengers Bangalore   
806          Sunrisers Hyderabad           bat          Sunrisers Hyderabad   
812               Delhi Capitals         field               Mumbai Indians   

    result  result_margin eliminator method                umpire1  \
0     runs          140.0          N    NaN              Asad Rauf   
1     runs           33.0          N    NaN              MR Benson   
9     runs           66.0          N    NaN              Aleem Dar   
18    runs           45.0          N    NaN            RE Koertzen   
37    runs           41.0          N    NaN               SJ Davis   
..     ...            ...        ...    ...                    ...   
802   runs           34.0          N    NaN  KN Ananthapadmanabhan   
803   runs           44.0          N    NaN  KN Ananthapadmanabhan   
804   runs           82.0          N    NaN         RK Illingworth   
806   runs           69.0          N    NaN           AK Chaudhary   
812   runs           57.0          N    NaN            CB Gaffaney   

            umpire2  
0       RE Koertzen  
1

In [35]:
# Data cleaning:

data = {'Name': ['John', 'Emily', 'Ryan'],
        'Age': [25, np.nan, 35],
        'City': ['New York', 'Paris', 'London']}
df = pd.DataFrame(data)

df.dropna()          # Remove rows with missing values

Name   Age      City
0  John  25.0  New York
2  Ryan  35.0    London

In [36]:
df.fillna(0)         # Fill missing values with 0

Name   Age      City
0   John  25.0  New York
1  Emily   0.0     Paris
2   Ryan  35.0    London

In [37]:
df['Age'].fillna(df['Age'].mean())  # Fill missing values in a specific column with the column's mean

0    25.0
1    30.0
2    35.0
Name: Age, dtype: float64

In [ ]:
# Data visualization:

df.plot(x='Age', y='Salary', kind='scatter')  # Scatter plot

df['City'].value_counts().plot(kind='bar')     # Bar

In [49]:
# Selecting specific columns:

data = {'Name': ['John', 'Emily', 'Ryan'],
        'Age': [25, np.nan, 35],
        'City': ['New York', 'Paris', 'London'],
       'Salary': [25000, 18756, 34580]}
df = pd.DataFrame(data)

df[['Name', 'Age']]  # Select only the 'Name' and 'Age' columns

Name   Age
0   John  25.0
1  Emily   NaN
2   Ryan  35.0

In [51]:
# Grouping and aggregation:

df.groupby('City')['Age'].mean()    # Calculate the mean age for each city

City
London      35.0
New York    25.0
Paris        NaN
Name: Age, dtype: float64

In [52]:
# multiple aggregations

df.groupby('City').agg({'Age': 'mean', 'Salary': 'sum'})  # Calculate multiple aggregations on different columns

Age  Salary
City                  
London    35.0   34580
New York  25.0   25000
Paris      NaN   18756

In [57]:
# Merging DataFrames:

df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['John', 'Emily', 'Ryan']})
df2 = pd.DataFrame({'ID': [2, 3, 4], 'Salary': [5000, 6000, 7000]})
merged_df = pd.merge(df1, df2, on='ID', how = 'left')  # Merge based on the 'ID' column

print(merged_df)

   ID   Name  Salary
0   1   John     NaN
1   2  Emily  5000.0
2   3   Ryan  6000.0


In [58]:
# Sorting Data 

df.sort_values(by='Age', ascending=False)  # Sort the DataFrame by 'Age' in descending order

Name   Age      City  Salary
2   Ryan  35.0    London   34580
0   John  25.0  New York   25000
1  Emily   NaN     Paris   18756

In [60]:
# Handling missing values:

df.dropna(subset=['Age'])    # Remove rows with missing values in the 'Age' column

Name   Age      City  Salary
0  John  25.0  New York   25000
2  Ryan  35.0    London   34580

In [61]:
df.fillna({'Salary': 0})     # Fill missing values in the 'Salary' column with 0

Name   Age      City  Salary
0   John  25.0  New York   25000
1  Emily   NaN     Paris   18756
2   Ryan  35.0    London   34580